### ISSUE TITLE
未登录状态下，设置展示顺序

### ISSUE THREAD

**Issue by osiren** [Bumblebee202111/doubean-public#3]
希望在未登录状态下，能够设置通过搜索进入小组后的默认展示顺序。目前是进入小组后可以更改展示顺序，但退出小组再重新进入,了，展示顺序会还原成“最后更新话题”。

**Comment by Bumblebee202111** [comment]
[新版](https://github.com/Bumblebee202111/doubean-public/releases/tag/v0.7.0(700))修复是修复了，但是貌似看错了您的问题。我只修复了小组->话题->小组后顺序又变成默认的问题，您是希望永久记住顺序是吧？另外各种排序方式的名称也改成了与官方一致，减轻心智负担。新增了热门（新帖）的顺序，我自己可能需要用到，也是用热门接口本地排的。)
此外，[上版本](https://github.com/Bumblebee202111/doubean-public/releases/tag/v0.6.4(604))在页面间导航用Jetpack Compose（最新技术）重写之后，又出现了头疼的返回丢失位置问题，有待深究。
> 通过搜索进入小组
可以试下收藏功能，是我为了给未root用户提供小组快捷入口以及给所有用户提供小组Tab快捷入口开发的本地功能，不用每次都进行搜索。

**Comment by osiren** [comment]
确实是返回后丢失位置了
